import Link from "next/link";
import { requireApprovedUser } from "../lib/access";
import { getDatabase } from "../lib/db";
import { listOrders } from "../lib/order-store";
import { AuthenticatedShell } from "./ui/authenticated-shell";
import { NewOrderButton } from "./orders/new-order-button";

export default async function Home() {
  const user = await requireApprovedUser();
  const orders = (await listOrders(getDatabase(), false)).filter(order => order.assignments.some(assignment => assignment.userId === user.id));
  const cards: { title: string; description: string; href?: string }[] = [{ title: "Sales Orders", description: "Create and manage active orders", href: "/sales-orders" }, { title: "Completed Sales Orders", description: "Find completed and voided orders", href: "/completed-orders" }, { title: "Price Books", description: "Yellow, Blue and White books" }, { title: "Calendar", description: "Management schedules" }, { title: "Time Off/Birthday Calendar", description: "Employee events and holidays" }, ...(user.role === "ADMIN" ? [{ title: "Reports", description: "Sales and product reporting" }, { title: "Administration", description: "Employees and application settings" }] : [])];
  return <AuthenticatedShell title="Dashboard" active="Dashboard" admin={user.role === "ADMIN"}><main className="screen-page"><div className="screen-heading"><div><p className="eyebrow">Carts and Parts Operations</p><h1>Dashboard</h1><p className="screen-caption">Your orders and operations in one place.</p></div><NewOrderButton /></div><div className="dashboard-cards">{cards.map(card => card.href ? <Link className="dashboard-card" key={card.title} href={card.href} prefetch={false}><div><h2>{card.title}</h2><p>{card.description}</p></div><span aria-hidden="true">→</span></Link> : <div className="dashboard-card card-upcoming" key={card.title}><div><h2>{card.title}</h2><p>{card.description}</p><small>Coming later</small></div></div>)}</div><section className="content-panel"><div className="panel-heading"><h2>Orders Assigned to You</h2><Link href="/sales-orders">View Sales Orders</Link></div>{orders.length ? <div className="table-scroll"><table><thead><tr><th>SO Number</th><th>Name</th><th>Status</th><th>Division</th></tr></thead><tbody>{orders.map(order => { const fields = order.fields as Record<string, string>; return <tr key={order.id}><td><Link href={`/orders/${order.id}`}>DEV-{String(order.number).padStart(6, "0")}</Link></td><td><Link href={`/orders/${order.id}`}>{order.name}</Link></td><td><span className={`status-box status-${fields.status.replaceAll(" ", "-")}`}>{fields.status}</span></td><td>{fields.division__1 || "—"}</td></tr>; })}</tbody></table></div> : <div className="empty-message">You have no active orders assigned.</div>}</section></main></AuthenticatedShell>;
}
